/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 client/public/hoodie-mindfull.glb --transform 
Files: client/public/hoodie-mindfull.glb [3.92MB] > /Users/ankitaditya/Documents/reference/product_site_react_threejs/hoodie-mindfull-transformed.glb [468KB] (88%)
*/

import React from 'react'
import { useGLTF, useTexture, Decal } from '@react-three/drei'
import state from '../store/index';
import { easing } from "maath";
import { useFrame } from "@react-three/fiber";
import { useSnapshot } from 'valtio';

export function Mindfull(props) {
  const snap = useSnapshot(state);
  const { nodes, materials } = useGLTF('/hoodie-mindfull-transformed.glb')
  useFrame((state, delta) =>
    {
      easing.dampC(materials['Material_0.002'].color, snap.color['hoodie'], 0.25, delta)
    }
  );
  const stateString = JSON.stringify(snap);
  return (
    <group {...props} key={stateString}>
      <mesh 
      castShadow
      geometry={nodes.Mesh_0002.geometry} 
      material={materials['Material_0.002']} 
      scale={0.4}
      material-roughness={1}
      dispose={null} />
    </group>
  )
}

useGLTF.preload('/hoodie-mindfull-transformed.glb')
