/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 client/public/hoodie-mindfull.glb --transform 
Files: client/public/hoodie-mindfull.glb [3.92MB] > /Users/ankitaditya/Documents/reference/product_site_react_threejs/hoodie-mindfull-transformed.glb [468KB] (88%)
*/

import React from 'react'
import { useGLTF, useTexture, Decal } from '@react-three/drei'
import state from '../store/index';
import { easing } from "maath";
import { useFrame } from "@react-three/fiber";
import { useSnapshot } from 'valtio';

export function Mindfull(props) {
  const snap = useSnapshot(state);
  const { nodes, materials } = useGLTF('/hoodie.glb')
  const logoTexture = useTexture(snap.logoDecal);
  const fullTexture = useTexture(snap.fullDecal);
  const baseTexture = useTexture(snap.baseDecal);
  useFrame((state, delta) =>
    {
      easing.dampC(nodes.mesh_0.material.color, snap.color['hoodie'], 0.1, delta)
    }
  );
  const stateString = JSON.stringify(snap);
  return (
    <group {...props} dispose={null} key={stateString}>
    <mesh
      castShadow
      // receiveShadow
      material-roughness={1}
      geometry={nodes.mesh_0.geometry}
      material={nodes.mesh_0.material}
      dispose={null}
      scale={0.7}
    >
      {snap.isBaseTexture && (
          <Decal
            position={[-0.01, 0.03, 0.10]}
            rotation={[0, 0, 0]}
            scale={0.4}
            map={baseTexture}
            map-anisotropy={16}
            depthTest={false}
            depthWrite={true}
          ></Decal>
        )}
        {snap.isFullTexture && (
          <Decal
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={1}
            map={fullTexture}
          ></Decal>
        )}
        {snap.isLogoTexture && (
          <Decal
            position={[0.11, 0.18, 0.10]}
            rotation={[0, 0, 0]}
            scale={0.15}
            map={logoTexture}
            map-anisotropy={16}
            depthTest={false}
            depthWrite={true}
          ></Decal>
        )}
    </mesh>
  </group>
  )
}

useGLTF.preload('/hoodie.glb')
