/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../public/jeans.glb --transform 
Files: ../../public/jeans.glb [45.64MB] > /Users/ankitaditya/Documents/reference/product_site_react_threejs/client/src/canvas/jeans-transformed.glb [3MB] (93%)
Author: Ret.ouchs (https://sketchfab.com/ret.ouchs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jeans-3b74e0d980754027bacbfd17b8dd0260
Title: Jeans
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import state from '../store/index';
import { easing } from "maath";
import { useFrame } from "@react-three/fiber";
import { useSnapshot } from 'valtio';

export function Jeans(props) {
  const snap = useSnapshot(state);
  const { nodes, materials } = useGLTF('/jeans-transformed.glb')
  useFrame((state, delta) =>
    {
      easing.dampC(materials.middle.color, snap.color['jeans'], 0.25, delta)
      easing.dampC(materials.back.color, snap.color['jeans'], 0.25, delta)
    }
  );
  const stateString = JSON.stringify(snap);
  return (
    <group {...props} key={stateString} dispose={null}>
      <mesh geometry={nodes.Object_15.geometry} material={materials.back} rotation={[Math.PI / 2, 0, 0]} scale={0.018} />
      {/* <mesh geometry={nodes.Object_4.geometry} material={materials.middle} rotation={[Math.PI / 2, 0, 0]} scale={0.018} /> */}
    </group>
  )
}

useGLTF.preload('/jeans-transformed.glb')
