/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 client/public/shirt_baked.glb --transform 
Files: client/public/shirt_baked.glb [1.05MB] > /Users/ankitaditya/Documents/reference/product_site_react_threejs/shirt_baked-transformed.glb [274.65KB] (74%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shirt_baked-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.T_Shirt_male.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('/shirt_baked-transformed.glb')
