/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/t-shirt-sports.glb --transform 
Files: public/t-shirt-sports.glb [40.1MB] > /Users/ankitaditya/Documents/reference/product_site_react_threejs/client/t-shirt-sports-transformed.glb [3.2MB] (92%)
Author: freemen (https://sketchfab.com/lox148822847)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/t-shirt-ea719760788f4562a905142422276e9e
Title: T-shirt
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function TSports(props) {
  const { nodes, materials } = useGLTF('/t-shirt-sports-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_7.geometry} material={materials['Default_Topstitch_2803.002']} position={[-0.002, 0, 0]} />
      <mesh geometry={nodes.Object_25.geometry} material={materials['Default_Topstitch_2747.001']} position={[-0.002, 0, 0]} />
      <mesh geometry={nodes.Object_111.geometry} material={materials.Cotton_Heavy_Twill_116740} position={[-0.002, 0, 0]} />
      <mesh geometry={nodes.Object_113.geometry} material={materials['Cotton_Heavy_Twill_116740.010']} position={[-0.002, 0, 0]} />
      <mesh geometry={nodes.Object_119.geometry} material={materials['Cotton_Heavy_Twill_116740.004']} position={[-0.002, 0, 0]} />
      <mesh geometry={nodes.Object_121.geometry} material={materials.Rib_1X1_486gsm_116764} position={[-0.002, 0, 0]} />
      <mesh geometry={nodes.Object_123.geometry} material={materials.Cotton_Heavy_Twill_Copy_1_116819} position={[-0.002, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/t-shirt-sports-transformed.glb')
