export const skills = [...new Set([
    "Accounting",
    "Active Listening",
    "Analytical Thinking",
    "Architectural Design",
    "Artistic Illustration",
    "Automotive Repair",
    "Baking",
    "Biochemical Analysis",
    "Budget Management",
    "Carpentry",
    "Computer Programming",
    "Conflict Resolution",
    "Content Creation",
    "Counseling",
    "Critical Thinking",
    "Culinary Arts",
    "Customer Service",
    "Data Analysis",
    "Database Management",
    "Dental Care",
    "Digital Marketing",
    "Editing",
    "Electrical Engineering",
    "Event Planning",
    "Financial Planning",
    "Firefighting",
    "First Aid",
    "Graphic Design",
    "Hair Styling",
    "Human Resources Management",
    "HVAC Repair",
    "Interior Design",
    "Inventory Management",
    "Journalism",
    "Language Translation",
    "Leadership",
    "Legal Research",
    "Machine Operation",
    "Marketing Strategy",
    "Mechanical Engineering",
    "Medical Diagnostics",
    "Music Composition",
    "Network Security",
    "Nursing Care",
    "Online Advertising",
    "Operating Heavy Machinery",
    "Painting",
    "Paralegal Services",
    "Photography",
    "Physical Therapy",
    "Plumbing",
    "Project Management",
    "Public Relations",
    "Real Estate Management",
    "Research Methodology",
    "Retail Management",
    "Robotics Engineering",
    "Sales Strategy",
    "Search Engine Optimization (SEO)",
    "Social Media Management",
    "Software Development",
    "Speech Writing",
    "Statistical Analysis",
    "Strategic Planning",
    "Teaching",
    "Technical Support",
    "Time Management",
    "Translation Services",
    "Transportation Logistics",
    "Travel Planning",
    "Urban Planning",
    "User Experience (UX) Design",
    "Veterinary Care",
    "Video Editing",
    "Virtual Assistance",
    "Voice Acting",
    "Web Development",
    "Welding",
    "Writing and Editing",
    "Yoga Instruction",
    "Zoological Research",
    "Agricultural Management",
    "Air Traffic Control",
    "Animation",
    "App Development",
    "Archaeological Research",
    "Astronomical Observation",
    "Aviation Navigation",
    "Bioinformatics",
    "Blockchain Development",
    "Chemical Engineering",
    "Cinematography",
    "Cloud Computing",
    "Cybersecurity",
    "Dietetics and Nutrition",
    "E-commerce Management",
    "Environmental Science",
    "Fashion Design",
    "Fitness Training",
    "Forensic Analysis",
    "JavaScript", 
    "Python", 
    "Java",
    "3D Modeling",
    "Abnormal Psychology",
    "Acoustical Engineering",
    "Actuarial Science",
    "Advertising",
    "Aerial Photography",
    "Agronomy",
    "Air Conditioning Repair",
    "Aircraft Maintenance",
    "Algorithm Design",
    "Allergy Testing",
    "Alternative Medicine",
    "Animal Husbandry",
    "Animation Design",
    "Antique Appraisal",
    "Apparel Design",
    "Arboriculture",
    "Artificial Intelligence",
    "Art Restoration",
    "Astrobiology",
    "Astrophysics",
    "Auctioneering",
    "Audio Engineering",
    "Auditing",
    "Auto Detailing",
    "AutoCAD",
    "Aviation Maintenance",
    "Bacteriology",
    "Ballistics",
    "Barista Skills",
    "Bartending",
    "Behavioral Analysis",
    "Biogeochemistry",
    "Biometrics",
    "Biomedical Engineering",
    "Blacksmithing",
    "Boat Repair",
    "Botany",
    "Brand Management",
    "Bridge Engineering",
    "Broadcast Journalism",
    "Building Inspection",
    "Business Analysis",
    "Business Development",
    "C++ Programming",
    "Cabinet Making",
    "Calligraphy",
    "Catering",
    "Ceramic Arts",
    "Chemical Analysis",
    "Childcare",
    "Chiropractic Care",
    "Cinematography",
    "Civil Engineering",
    "Classical Music Performance",
    "Climate Science",
    "Cloud Architecture",
    "Coaching",
    "Commercial Diving",
    "Commercial Piloting",
    "Community Outreach",
    "Computer Forensics",
    "Construction Management",
    "Consumer Behavior Analysis",
    "Content Management",
    "Copywriting",
    "Corporate Law",
    "Costume Design",
    "Crisis Management",
    "Cryptocurrency Trading",
    "Cryptography",
    "Cultural Anthropology",
    "Curriculum Development",
    "Customer Relationship Management",
    "Cyber Law",
    "Dairy Farming",
    "Data Mining",
    "Data Science",
    "Database Administration",
    "Deckhand Skills",
    "Deep Learning",
    "Demography",
    "Dental Hygiene",
    "Dermatology",
    "Desktop Publishing",
    "Detective Work",
    "Diet Planning",
    "Digital Illustration",
    "Disaster Recovery",
    "Documentary Filmmaking",
    "Drone Piloting",
    "Eco-Friendly Design",
    "Ecotourism",
    "Editing and Proofreading",
    "Education Administration",
    "Electric Guitar Repair",
    "Electrical Wiring",
    "Electronics Repair",
    "Emergency Medical Services",
    "Emergency Planning",
    "Endocrinology",
    "Energy Management",
    "Engineering Design",
    "Environmental Health",
    "Epidemiology",
    "Ergonomics",
    "Estate Planning",
    "Ethical Hacking",
    "Event Coordination",
    "Executive Coaching",
    "Exercise Physiology",
    "Explosives Handling",
    "Facilities Management",
    "Fashion Merchandising",
    "Film Direction",
    "Film Production",
    "Financial Analysis",
    "Fine Arts Restoration",
    "Fire Safety",
    "Fishery Management",
    "Floral Design",
    "Food Safety",
    "Forestry",
    "Freelance Writing",
    "Fundraising",
    "Furniture Design",
    "Game Development",
    "Genealogy",
    "Genetic Counseling",
    "Genetics",
    "Geographic Information Systems (GIS)",
    "Geology",
    "Gerontology",
    "Glass Blowing",
    "Golf Course Management",
    "Government Relations",
    "Graphic Facilitation",
    "Green Building",
    "Green Energy",
    "Guitar Teaching",
    "Handwriting Analysis",
    "Health Administration",
    "Health Coaching",
    "Health Informatics",
    "Healthcare Management",
    "Heavy Equipment Operation",
    "Hematology",
    "Herbal Medicine",
    "Herpetology",
    "Highway Engineering",
    "Histology",
    "Horticulture",
    "Hospital Administration",
    "Hostel Management",
    "Hotel Management",
    "Housekeeping",
    "Human Factors Engineering",
    "Hydraulic Engineering",
    "Hydrology",
    "Hyperbaric Medicine",
    "Illustration",
    "Immunology",
    "Industrial Design",
    "Industrial Hygiene",
    "Information Security",
    "Information Systems Management",
    "Insurance Underwriting",
    "Interior Architecture",
    "International Business",
    "International Law",
    "Internet of Things (IoT)",
    "iOS Development",
    "Jewelry Design",
    "Journalistic Writing",
    "Kitchen Design",
    "Laboratory Analysis",
    "Landscape Architecture",
    "Landscape Photography",
    "Landscaping",
    "Law Enforcement",
    "Leatherworking",
    "Librarianship",
    "Life Coaching",
    "Linguistics",
    "Literary Analysis",
    "Litigation",
    "Logistics Management",
    "Machine Learning",
    "Magnetic Resonance Imaging (MRI)",
    "Makeup Artistry",
    "Marine Biology",
    "Marine Engineering",
    "Marine Navigation",
    "Market Research",
    "Mathematical Modeling",
    "Mechanical Drafting",
    "Medical Coding",
    "Medical Imaging",
    "Medical Research",
    "Metalworking",
    "Microbiology",
    "Mobile App Development",
    "Mortgage Lending",
    "Motion Graphics",
    "Museum Curation",
    "Music Arrangement",
    "Music Therapy",
    "Nanotechnology",
    "Negotiation",
    "Neonatal Care",
    "Nephrology",
    "Neurology",
    "Nuclear Engineering",
    "Nuclear Medicine",
    "Numerical Analysis",
    "Nutritional Counseling",
    "Obstetrics",
    "Oceanography",
    "Oncology",
    "Opera Singing",
    "Operations Management",
    "Optometry",
    "Oral Surgery",
    "Organizational Development",
    "Orthodontics",
    "Orthopedic Surgery",
    "Osteopathy",
    "Outdoor Education",
    "Paragliding",
    "Park Management",
    "Patent Law",
    "Pathology",
    "Pediatric Nursing",
    "Pediatrics",
    "Pet Grooming",
    "Pharmaceutical Sales",
    "Pharmacology",
    "Philanthropy",
    "Photojournalism",
    "Physical Chemistry",
    "Physiotherapy",
    "Pilates Instruction",
    "Plant Pathology",
    "Plastic Surgery",
    "Playwriting",
    "Podcasting",
    "Political Campaign Management",
    "Political Science",
    "Portrait Photography",
    "Post-Production Editing",
    "Primary Education",
    "Private Investigation",
    "Process Improvement",
    "Product Management",
    "Professional Networking",
    "Project Coordination",
    "Psychiatry",
    "Public Health",
    "Public Policy Analysis",
    "Public Speaking",
    "Publishing",
    "Quality Assurance",
    "Radiation Therapy",
    "Radiologic Technology",
    "Real Estate Appraisal",
    "Recruiting",
    "Reflexology",
    "Regulatory Affairs",
    "Rehabilitation Counseling",
    "Remote Sensing",
    "Renewable Energy",
    "Restaurant Management",
    "Retail Buying",
    "Risk Assessment",
    "Robotic Process Automation",
    "Roofing",
    "Safety Engineering",
    "Sales Forecasting",
    "Scenic Design",
    "Scientific Research",
    "Screen Printing",
    "Screenwriting",
    "Scriptwriting",
    "Security Analysis",
    "Security Consulting",
    "Set Design",
    "Sewing",
    "Shakespearean Acting",
    "SharePoint Administration",
    "Ship Navigation",
    "Social Work",
    "Software Quality Assurance",
    "Solar Energy",
    "Sound Design",
    "Special Effects Makeup",
    "Speech Therapy",
    "Sports Coaching",
    "Stained Glass Making",
    "Statistical Modeling",
    "Stock Trading",
    "Strategic Marketing",
    "Structural Engineering",
    "Supply Chain Management",
    "Surgical Assisting",
    "Surveying",
    "Sustainable Agriculture",
    "System Administration",
    "Systems Analysis",
    "Tailoring",
    "Tax Consulting",
    "Tax Preparation",
    "Taxidermy",
    "Teacher Training",
    "Technical Illustration",
    "Telecommunications",
    "Television Production",
    "Textile Design",
    "Theatrical Directing",
    "Thermodynamics",
    "Tour Guiding",
    "Tourism Management",
    "Trade Compliance",
    "Training Development",
    "Transcription",
    "Transportation Engineering",
    "Travel Writing",
    "Tree Surgery",
    "UI Design",
    "User Research",
    "UX Research",
    "Veterinary Surgery",
    "Victim Advocacy",
    "Video Game Design",
    "Video Production",
    "Virtual Reality Development",
    "Voice Over",
    "Warehouse Management",
    "Waste Management",
    "Water Treatment",
    "Wildlife Conservation",
    "Wind Energy",
    "Wine Making",
    "Woodworking",
    "Workplace Safety",
    "Yoga Instruction",
    "Youth Counseling",
    "Zoology"
  ])];